### PR TITLE
Fix format handling

### LINKED ISSUE #251: JSON ingestion mapping conflict with file format MultiJSON
**Describe the bug**

When file format is MultiJSON and ingestion mapping type is JSON, a error is returned: `BadRequest_NoRecordsOrWrongFormat: The input stream produced 0 bytes. This usually means that the input JSON stream was ill formed.` Seems that the IngestionMapping option [set both IngestionMappingType and Format to the same `mappingKind`](https://github.com/Azure/azure-kusto-go/blob/69ccd072cfaa6ef1c66360102b887ad15dbc5c8f/kusto/ingest/file_options.go#L244C1-L245C47). And I can't put FileFormat option at the end because `format and ingestion mapping type must match (hint: using ingestion mapping sets the format automatically)`.

**To Reproduce**

```Golang
options := []ingest.FileOption{
    ingest.FlushImmediately(),
    ingest.FileFormat(ingest.MultiJSON),
    ingest.IngestionMapping(mapping, ingest.JSON),
    ingest.ReportResultToTable(),
  }

result, err := in.FromFile(ctx, dataPath, options...)
if err != nil {
    return fmt.Errorf("failed to ingest data: %w", err)
}
```

**Expected behavior**

Ingestion is successful when file format is MultiJSON and ingestion mapping type is JSON. The v0.5.2 we used before was fine.

### PR DESCRIPTION
**Pull request by AsafMah**
fixes #251

### CODE REVIEW

File: azkustoingest/file_options.go [hunk 1]
```diff
@@ -229,16 +229,18 @@ func InferFormatFromFileName(fName string) DataFormat {
 // IngestionMapping provides runtime mapping of the data being imported to the fields in the table.
 // "ref" will be JSON encoded, so it can be any type that can be JSON marshalled. If you pass a string
 // or []byte, it will be interpreted as already being JSON encoded.
-// mappingKind can only be: CSV, JSON, AVRO, Parquet or ORC.
+// mappingKind can only be: CSV, JSON, AVRO, Parquet or ORC, but it will be automatically converted from other types.
 // The mappingKind parameter will also automatically set the FileFormat option.
```
Comment (ohadbitt) [inline azkustoingest/file_options.go:233]: First line is just confusing
```suggestion
// The format parameter will automatically set the FileOption.Format option.
```

File: azkustoingest/file_options.go [hunk 2]
```diff
@@ -229,16 +229,18 @@ func InferFormatFromFileName(fName string) DataFormat {
 // IngestionMapping provides runtime mapping of the data being imported to the fields in the table.
 // "ref" will be JSON encoded, so it can be any type that can be JSON marshalled. If you pass a string
```
Comment (ohadbitt) [inline azkustoingest/file_options.go:230]:
```suggestion
// IngestionMapping provides runtime mapping of the data being imported to the columns in the table.
// "mapping" will be JSON encoded, so it can be any type that can be JSON marshalled. If you pass a string
```

File: azkustoingest/file_options.go [hunk 3]
```diff
@@ -273,18 +275,19 @@ func IngestionMapping(mapping interface{}, mappingKind DataFormat) FileOption {
 }
 
 // IngestionMappingRef provides the name of a pre-created mapping for the data being imported to the fields in the table.
-// mappingKind can only be: CSV, JSON, AVRO, Parquet or ORC.
+// mappingKind can only be: CSV, JSON, AVRO, Parquet or ORC, but it will be automatically converted from other types.
 // For more details, see: https://docs.microsoft.com/en-us/azure/kusto/management/create-ingestion-mapping-command
 // The mappingKind parameter will also automatically set the FileFormat option.
```
Comment (ohadbitt) [inline azkustoingest/file_options.go:280]:
```suggestion
// For more details, see: https://docs.microsoft.com/azure/kusto/management/create-ingestion-mapping-command
// The formatparameter will also automatically set the FileOption.Format option.
```

File: azkustoingest/file_options_test.go [hunk 4]
```diff
@@ -201,6 +201,27 @@ func TestFileFormatAndMapping(t *testing.T) {
...
 		},
+		{
+			desc:                "Test multijson with default",
+			options:             []FileOption{IngestionMapping("mapping", MultiJSON)},
+			source:              FromFile,
+			expectedFormat:      MultiJSON,
+			expectedMappingType: JSON,
+		},
+		{
+			desc:                "Test multijson with before",
```
Comment (ohadbitt) [inline azkustoingest/file_options_test.go:212]:
```suggestion
			desc:                "Test multijson with with FileFormat set before",
```

File: azkustoingest/internal/properties/properties.go [hunk 5]
```diff
@@ -160,13 +160,13 @@ func (d DataFormat) MarshalJSON() ([]byte, error) {
 	return []byte(fmt.Sprintf("%q", d.String())), nil
 }
 
-// IsValidMappingKind returns true if a dataformat can be used as a MappingKind.
-func (d DataFormat) IsValidMappingKind() bool {
+// MappingKind returns true if a dataformat can be used as a MappingKind.
```
Comment (ohadbitt) [inline azkustoingest/internal/properties/properties.go:163]:
```suggestion
// MappingKind returns the mapping kind associated with this DataFormat```
